# Generated by Django 2.2.15 on 2020-11-30 09:44

from django.conf import settings
from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('quote', models.CharField(blank=True, max_length=200)),
                ('profile_image', models.ImageField(default='default_m.png', upload_to=home.models.Profile.profile_image_directory_path)),
                ('profile_cover', models.ImageField(default='/static/images/cover.png', upload_to=home.models.Profile.profile_cover_directory_path)),
                ('intro', models.TextField(blank=True, verbose_name='Intro')),
                ('storyline', models.TextField(blank=True, verbose_name='Storyline')),
                ('fb', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Facebook')),
                ('twitter', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Twitter')),
                ('google', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Google')),
                ('insta', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Instagram')),
                ('github', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Github')),
                ('linkedin', models.CharField(blank=True, max_length=100, unique=True, verbose_name='LinkedIn')),
                ('user', models.OneToOneField(on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.CharField(choices=[('Product', 'Product'), ('Service', 'Service')], default='Product', max_length=10)),
                ('profile', models.ForeignKey(on_delete='CASCADE', to='home.Profile')),
            ],
        ),
    ]
